version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-credentials/url

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "正在安装环境依赖..."
      - pip install --upgrade pip
      - # 安装项目业务依赖
      - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - # 安装质量检查工具
      - pip install flake8 bandit mypy pytest pytest-cov

  pre_build:
    commands:
      - echo "开始代码质量检查..."
      
      - echo "运行安全扫描 (Bandit)..."
      - bandit -r . -f txt || echo "Bandit 扫描发现问题，请检查输出"
      
      - echo "运行代码风格检查 (Flake8)..."
      - # 检查语法错误、未定义的变量等严重问题
      - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - # 检查 PEP8 规范（可选，如果不通过会终止构建）
      - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - echo "运行静态类型检查 (Mypy)..."
      - # 注意：如果项目没写 Type Hints，这一步可以先注释掉
      - mypy . --ignore-missing-imports || echo "Mypy 检查失败，跳过（如果项目没有类型提示，这是正常的）"

  build:
    commands:
      - echo "开始运行单元测试 (Pytest)..."
      # 即使没有找到测试文件，也会返回 0 (成功)，不会中断构建
      - pytest --cov=./ --cov-report=term-missing || echo "未找到测试用例，跳过测试。"
      

      - echo "正在执行构建/打包逻辑..."

      - echo "使用管道符传递密码进行非交互式登录..."
      # 处理 registry URL：去掉协议部分（http:// 或 https://），因为 Docker 镜像名称不能包含协议
      - REGISTRY_HOST=`echo $DOCKER_REGISTRY_URL | sed 's|^https\?://||'`
      - export REGISTRY_HOST
      # 使用管道符传递密码进行非交互式登录（docker login 可以接受带协议的 URL）
      - echo $DOCKER_REGISTRY_PASSWORD | docker login --username $DOCKER_REGISTRY_USERNAME --password-stdin $DOCKER_REGISTRY_URL
      
      - echo "构建Docker镜像..."
      # Docker 镜像名称格式：registry-host/username/repo:tag（不能包含协议）
      - docker build -t "$REGISTRY_HOST/$DOCKER_REGISTRY_USERNAME/docker-python-hello-world:latest" .

      - echo "上传Docker镜像..."
      - docker push "$REGISTRY_HOST/$DOCKER_REGISTRY_USERNAME/docker-python-hello-world:latest"

  post_build:
    commands:
      - bash -c 'echo "构建与检查流程于 $(date +%Y-%m-%d-%H:%M:%S) 完成"'
      # 测试一串日期格式
      - echo "Date debug test start"
      - echo "Test 1 - Direct date command"
      - date
      - echo "Test 2 - Using bash -c for command substitution"
      - bash -c 'echo "Date is $(date)"'
      - echo "Test 3 - Using bash -c for formatted date"
      - bash -c 'echo "Date is $(date +%Y-%m-%d-%H:%M:%S)"'
      - echo "Test 4 - Variable assignment"
      - BUILD_DATE=$(date +%Y-%m-%d-%H:%M:%S)
      - echo "Date is $BUILD_DATE"
      - echo "Test 5 - Export variable"
      - export BUILD_DATE=$(date +%Y-%m-%d-%H:%M:%S)
      - echo "Date is $BUILD_DATE"
      - echo "Test 6 - Final format Chinese message"
      - echo "Date debug test end"

# artifacts:
  # 对于 Docker 项目，镜像已推送到 registry，通常不需要保存构建产物
  # 如果需要保存测试报告或日志，取消下面的注释：
  # files:
  #   - 'test-reports/**/*'
  #   - 'coverage/**/*'
  #   - '*.log'

cache:
  paths:
    - '/root/.cache/pip' # 缓存 pip 依赖，加速下次构建